### ISSUE TITLE
Feature request: Use release versions

### ISSUE THREAD

**Issue by jihonrado** [lolouk44/xiaomi_mi_scale#14]
Coult it be possible to keep all versions on [Docker Hub](https://hub.docker.com/r/lolouk44/xiaomi-mi-scale)? Currently, only the `latest` version is available. If previous versions were available, we would be able to:

- Have stability, as there would not be risk of upgrading to a non backwards-compatible version.
- Have traceability, which in conjuntion with [Github releases/Git tags](https://github.com/lolouk44/xiaomi_mi_scale/releases) and even changelogs, it would be very powerful.
- Go back to previous versions to avoid bugs introduced in new versions (I am experiencing #13) or for debugability purposes.

Thanks!

**Comment by lolouk44** [comment]
Thanks, will add releases going forward

**Comment by lolouk44** [comment]
Thanks again for your feedback. I've now added releases to the repo and to the docker hub.
I've not tagged the latest release (`0.1.1`) as `:latest` on docker hub while I run some tests with a few users. Feel free to try though and let me know how it goes

**Comment by jihonrado** [comment]
Thanks @lolouk44, great news. I pinned `0.1.1` version on my set up but I am still unable to test it because I am still experiencing #13.

**Comment by lolouk44** [comment]
what errors are displayed?

**Comment by jihonrado** [comment]
Sorry @lolouk44, turns out that I did not recreate properly the container in docker-compose. I forced a container recreation with the  `0.1.1` version and it works now. The data now flows from the service to MQTT. No more `Error while running the script, continuing. If you see this message too often/constantly there is probably a real issue...` errors, as explained in #13.

For completion:

- `latest` does not work (#13)
- `0.1.0` does not work (#13)
- `0.1.1` works

Could it be something you fixed in c47614f?

**Comment by lolouk44** [comment]
> * `latest` does not work (#13)

not pushed 0.1.1 to latest yet, wanted to test before pushing it to the masses :)



> Could it be something you fixed in [c47614f](https://github.com/lolouk44/xiaomi_mi_scale/commit/c47614f196116f62d1751b48c3c5a44630aaaab9)?

most definitely. Did a few changes that should make the connection more stable and I've also added a way to reset the BT interface (hciconfig hci0 reset) if I get 5 consecutive BT management errors...
That said I still experienced issues last night where I actually had to reboot the PI to be able to turn BT back on...
There are issues with bluepy that screws the BT interface, and by the looks of it, it doesn't look like the owner is maintaining it ([155  open issues](https://github.com/IanHarvey/bluepy/issues), 16 open PRs)


> * `0.1.1` works

Great, I'll finally close this issue :)
